"""'Init'

Revision ID: feec33dcec39
Revises: b7d5cfa3fc1f
Create Date: 2024-05-10 03:00:10.275027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feec33dcec39'
down_revision: Union[str, None] = 'b7d5cfa3fc1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('contacts', 'phone',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'phone',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.drop_column('contacts', 'updated_at')
    # ### end Alembic commands ###
